/**
 * Seed script — populates the database with all 24 jobs from the frontend data.ts
 * Run with: npm run seed
 */

require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('./config/db').default;
const Job = require('./models/Job').default;
const User = require('./models/User').default;

const jobs = [
  {
    title: 'Senior Product Designer',
    company: 'Stripe',
    logo: '/icons/FeaturedJobs/Company Logo.svg',
    location: 'San Francisco, US',
    type: 'Full Time',
    category: 'Design',
    salary: '$90k – $120k',
    postedAt: '2 days ago',
    description:
      'Stripe is looking for a Senior Product Designer to craft elegant, user-centered interfaces across our payments platform. You\'ll work closely with engineering and product teams.',
    tags: ['Design', 'Figma', 'UI/UX'],
    featured: true,
    aboutCompany:
      'Stripe is a financial infrastructure platform for businesses. Millions of companies—from the world\'s largest enterprises to the most ambitious startups—use Stripe to accept payments, grow their revenue, and accelerate new business opportunities.',
    experience: '4+ years',
    companySize: '4,000 – 6,000 employees',
    companyWebsite: 'https://stripe.com',
    applicants: 148,
    responsibilities: [
      'Design end-to-end user experiences across web and mobile products.',
      'Collaborate with engineers and PMs to deliver polished, pixel-perfect interfaces.',
      'Conduct user research and usability testing to validate design decisions.',
      'Create and maintain design system components in Figma.',
      'Present design concepts to stakeholders and incorporate feedback effectively.',
    ],
    requirements: [
      '4+ years of product design experience at a tech company.',
      'Strong portfolio demonstrating UI/UX problem-solving.',
      'Proficiency in Figma and prototyping tools.',
      'Experience designing complex B2B or fintech products.',
      'Excellent communication and collaboration skills.',
    ],
    niceToHave: [
      'Experience with motion design or micro-interactions.',
      'Familiarity with front-end technologies (HTML, CSS, React).',
      'Prior experience working in a fintech or payments company.',
    ],
    benefits: [
      'Comprehensive health, dental & vision insurance.',
      'Generous equity package.',
      'Flexible remote work policy.',
      'Annual learning & development stipend ($2,000).',
      'Home office setup budget.',
      'Unlimited PTO with a recommended minimum.',
    ],
  },
  {
    title: 'Frontend Engineer',
    company: 'Vercel',
    logo: '/icons/FeaturedJobs/Dropbox.svg',
    location: 'Remote',
    type: 'Remote',
    category: 'Engineering',
    salary: '$110k – $150k',
    postedAt: '1 day ago',
    description:
      'Join Vercel\'s product team as a Frontend Engineer. You\'ll be building blazing fast web experiences using Next.js, React, and TypeScript.',
    tags: ['React', 'TypeScript', 'Next.js'],
    featured: true,
    aboutCompany:
      'Vercel is the platform for frontend developers, providing the speed and reliability innovators need to create at the moment of inspiration.',
    experience: '3+ years',
    companySize: '500 – 1,000 employees',
    companyWebsite: 'https://vercel.com',
    applicants: 231,
    responsibilities: [
      'Build and maintain high-performance UI components in React and TypeScript.',
      'Contribute to open-source Next.js projects and internal tooling.',
      'Optimize for performance, accessibility, and developer experience.',
      'Collaborate with design and backend teams in an async-first environment.',
      'Write thorough tests and documentation for all production code.',
    ],
    requirements: [
      '3+ years of frontend engineering experience.',
      'Deep knowledge of React, TypeScript, and modern CSS.',
      'Familiarity with Next.js and Edge runtime concepts.',
      'Strong understanding of web performance and Core Web Vitals.',
      'Experience with CI/CD pipelines and deployment workflows.',
    ],
    niceToHave: [
      'Contributions to open-source projects.',
      'Experience with Turbopack or Webpack internals.',
      'Knowledge of WebAssembly.',
    ],
    benefits: [
      '100% remote — work from anywhere in the world.',
      'Competitive salary + meaningful equity.',
      'Top-tier health, dental, and vision coverage.',
      '$500/month stipend for remote work setup.',
      'Annual team retreats.',
      'Generous parental leave policy.',
    ],
  },
  {
    title: 'Growth Marketing Manager',
    company: 'Revolut',
    logo: '/icons/FeaturedJobs/Company Logo-1.svg',
    location: 'London, UK',
    type: 'Full Time',
    category: 'Marketing',
    salary: '£70k – £90k',
    postedAt: '3 days ago',
    description:
      'Revolut is seeking a data-driven Growth Marketing Manager to lead user acquisition campaigns across paid, organic, and referral channels globally.',
    tags: ['Marketing', 'Growth', 'Analytics'],
    featured: false,
    aboutCompany:
      'Revolut is a fintech super-app with 35+ million customers globally.',
    experience: '3+ years',
    companySize: '6,000+ employees',
    companyWebsite: 'https://revolut.com',
    applicants: 94,
    responsibilities: [
      'Own and scale paid acquisition channels (Google, Meta, TikTok).',
      'Develop referral and lifecycle marketing programs to boost LTV.',
      'Analyse funnel performance and translate insights into growth experiments.',
      'Collaborate with design, data, and product teams on campaign execution.',
      'Report on key growth metrics to senior leadership weekly.',
    ],
    requirements: [
      '3+ years in growth or performance marketing.',
      'Hands-on experience managing large-scale paid ad budgets.',
      'Strong analytical skills — comfortable with SQL and BI tools.',
      'Experience running A/B tests and multivariate experiments.',
      'Excellent written and verbal communication skills.',
    ],
    niceToHave: [
      'Experience in fintech or subscription businesses.',
      'Knowledge of attribution modelling (MMM, MTA).',
      'Familiarity with Braze or Iterable for lifecycle campaigns.',
    ],
    benefits: [
      'Competitive salary + performance bonus.',
      'Revolut premium account on us.',
      'Flexible hybrid working (2 days in-office).',
      'Private health insurance.',
      'Generous learning budget.',
      'Global team retreats twice a year.',
    ],
  },
  {
    title: 'Data Scientist',
    company: 'Spotify',
    logo: '/icons/FeaturedJobs/Company Logo-2.svg',
    location: 'New York, US',
    type: 'Full Time',
    category: 'Technology',
    salary: '$130k – $170k',
    postedAt: '5 days ago',
    description:
      "Spotify's data team is hiring a Data Scientist to build models that power music recommendations for over 400 million users worldwide.",
    tags: ['Python', 'ML', 'Data'],
    featured: true,
    aboutCompany:
      'Spotify is the world\'s most popular audio streaming subscription service with 600 million users across 180+ markets.',
    experience: '5+ years',
    companySize: '9,000+ employees',
    companyWebsite: 'https://spotify.com',
    applicants: 312,
    responsibilities: [
      'Build and evaluate recommendation models at scale for 400M+ users.',
      'Collaborate with ML engineers to deploy models into production.',
      'Perform exploratory data analysis to identify patterns and insights.',
      'Design and analyse A/B experiments to measure model impact.',
      'Present data-driven findings to non-technical stakeholders.',
    ],
    requirements: [
      '5+ years of data science or ML experience.',
      'Proficiency in Python (pandas, scikit-learn, PyTorch or TensorFlow).',
      'Strong statistics foundations and experimental design knowledge.',
      'Experience working with large-scale data pipelines (Spark, Databricks).',
    ],
    niceToHave: [
      'Experience with audio ML or NLP.',
      'Publications in top ML conferences (NeurIPS, ICML, etc.).',
      'Knowledge of causal inference methods.',
    ],
    benefits: [
      'Spotify Premium subscription for you and a family member.',
      'Stock options with a 4-year vesting schedule.',
      'Flexible work from home policy.',
      'Monthly wellness allowance.',
    ],
  },
  {
    title: 'Brand Designer',
    company: 'Dropbox',
    logo: '/icons/FeaturedJobs/Company Logo-3.svg',
    location: 'San Francisco, US',
    type: 'Full Time',
    category: 'Design',
    salary: '$80k – $105k',
    postedAt: '1 week ago',
    description:
      "Dropbox is looking for a Brand Designer to evolve and extend our visual identity across marketing materials, product launching, and more.",
    tags: ['Design', 'Branding', 'Illustration'],
    featured: false,
    aboutCompany: 'Dropbox is the world\'s first smart workspace with more than 700 million registered users.',
    experience: '3+ years',
    companySize: '2,500 – 3,000 employees',
    companyWebsite: 'https://dropbox.com',
    applicants: 76,
    responsibilities: [
      'Create compelling visual assets for marketing campaigns.',
      'Extend and maintain Dropbox\'s brand identity guidelines.',
      'Design for product launches, social media, and events.',
    ],
    requirements: [
      '3+ years of brand or graphic design experience.',
      'Strong portfolio with diverse brand/identity work.',
      'Mastery of Adobe Creative Suite and Figma.',
    ],
    niceToHave: ['Motion design or video editing skills.', 'Experience with 3D design tools.'],
    benefits: ['Virtual-first work culture.', 'Comprehensive medical, dental, and vision.'],
  },
  {
    title: 'Backend Engineer',
    company: 'Notion',
    logo: '/icons/FeaturedJobs/Company Logo-4.svg',
    location: 'Remote',
    type: 'Remote',
    category: 'Engineering',
    salary: '$120k – $160k',
    postedAt: '4 days ago',
    description:
      'Notion is hiring a Backend Engineer to design and build scalable APIs that power our all-in-one productivity tool used by millions of teams.',
    tags: ['Node.js', 'PostgreSQL', 'API'],
    featured: false,
    aboutCompany: 'Notion is on a mission to make it possible for every person and company to tailor their tools.',
    experience: '4+ years',
    companySize: '500 – 800 employees',
    companyWebsite: 'https://notion.so',
    applicants: 189,
    responsibilities: [
      'Design, build, and maintain highly available RESTful and GraphQL APIs.',
      'Own and improve database performance for PostgreSQL at scale.',
    ],
    requirements: [
      '4+ years of backend engineering experience.',
      'Strong proficiency in Node.js or TypeScript.',
    ],
    niceToHave: ['Experience with real-time collaboration systems.'],
    benefits: ['Competitive salary and equity package.', 'Fully remote — flexible schedule.'],
  },
  {
    title: 'Financial Analyst',
    company: 'Airbnb',
    logo: '/icons/FeaturedJobs/Company Logo-5.svg',
    location: 'New York, US',
    type: 'Full Time',
    category: 'Finance',
    salary: '$95k – $125k',
    postedAt: '2 days ago',
    description:
      "Airbnb's finance team is seeking a sharp Financial Analyst to support FP&A, budgeting, and strategic financial planning.",
    tags: ['Finance', 'Excel', 'FP&A'],
    featured: false,
    aboutCompany: 'Airbnb is a global travel community with 5 million hosts and 1.5 billion guest arrivals.',
    experience: '2+ years',
    companySize: '6,000+ employees',
    companyWebsite: 'https://airbnb.com',
    applicants: 62,
    responsibilities: [
      'Support monthly and quarterly financial close and reporting.',
      'Build and maintain financial models for budgeting and forecasting.',
    ],
    requirements: [
      '2+ years in FP&A, corporate finance, or investment banking.',
      'Advanced Excel and financial modelling skills.',
    ],
    niceToHave: ['Experience with Anaplan or Workday Adaptive.'],
    benefits: ['Annual travel credit for Airbnb bookings.', 'Competitive base + annual bonus.'],
  },
  {
    title: 'Sales Development Representative',
    company: 'HubSpot',
    logo: '/icons/FeaturedJobs/Company Logo-6.svg',
    location: 'Berlin, Germany',
    type: 'Full Time',
    category: 'Sales',
    salary: '€45k – €65k',
    postedAt: '6 days ago',
    description:
      "HubSpot is growing its European sales team. As an SDR, you'll prospect and qualify outbound leads.",
    tags: ['Sales', 'CRM', 'Outbound'],
    featured: false,
    aboutCompany: 'HubSpot is the customer platform that helps businesses grow better.',
    experience: '1+ year',
    companySize: '7,000+ employees',
    companyWebsite: 'https://hubspot.com',
    applicants: 53,
    responsibilities: [
      'Research, identify, and prospect into target accounts.',
      'Qualify inbound leads and schedule meetings for Account Executives.',
    ],
    requirements: ['1+ year in a sales or customer-facing role.', 'Strong written English and German.'],
    niceToHave: ['Previous B2B SaaS SDR experience.'],
    benefits: ['Base salary + uncapped commission.', 'Clear promotion path to AE within 12–18 months.'],
  },
  {
    title: 'DevOps Engineer',
    company: 'Hashicorp',
    logo: '/icons/FeaturedJobs/Company Logo.svg',
    location: 'Remote',
    type: 'Remote',
    category: 'Engineering',
    salary: '$115k – $145k',
    postedAt: '3 days ago',
    description:
      "HashiCorp is looking for a DevOps Engineer to maintain and scale our cloud infrastructure using Terraform, Vault, and Kubernetes.",
    tags: ['Kubernetes', 'Terraform', 'AWS'],
    featured: false,
    aboutCompany: 'HashiCorp provides infrastructure automation software for multi-cloud environments.',
    experience: '4+ years',
    companySize: '1,500 – 2,500 employees',
    companyWebsite: 'https://hashicorp.com',
    applicants: 107,
    responsibilities: [
      'Design and maintain CI/CD pipelines for production and staging environments.',
      'Manage Kubernetes clusters on AWS and GCP.',
    ],
    requirements: [
      '4+ years of DevOps or SRE experience.',
      'Deep expertise in Kubernetes and Docker.',
    ],
    niceToHave: ['HashiCorp certifications.'],
    benefits: ['Remote-first culture.', 'Competitive salary and equity.'],
  },
  {
    title: 'UX Researcher',
    company: 'Figma',
    logo: '/icons/FeaturedJobs/Dropbox.svg',
    location: 'San Francisco, US',
    type: 'Full Time',
    category: 'Design',
    salary: '$100k – $130k',
    postedAt: '1 week ago',
    description:
      "Figma is searching for a UX Researcher to conduct usability studies and synthesise insights that shape our collaborative design tool.",
    tags: ['Research', 'UX', 'User Testing'],
    featured: true,
    aboutCompany: 'Figma is a collaborative design tool built for the web.',
    experience: '3+ years',
    companySize: '1,000 – 1,500 employees',
    companyWebsite: 'https://figma.com',
    applicants: 88,
    responsibilities: [
      'Plan and conduct generative and evaluative user research studies.',
      'Synthesise qualitative and quantitative data into actionable insights.',
    ],
    requirements: [
      '3+ years of UX research experience.',
      'Expertise in research methods (interviews, surveys, usability tests).',
    ],
    niceToHave: ['Experience with quantitative research or data analysis.'],
    benefits: ['Figma Teams subscription.', 'Annual $2,500 learning and development budget.'],
  },
  {
    title: 'Content Marketing Specialist',
    company: 'Buffer',
    logo: '/icons/FeaturedJobs/Company Logo-1.svg',
    location: 'Remote',
    type: 'Remote',
    category: 'Marketing',
    salary: '$60k – $80k',
    postedAt: '5 days ago',
    description: "Buffer is hiring a Content Marketing Specialist to write blog posts and social content.",
    tags: ['Content', 'SEO', 'Writing'],
    featured: false,
    aboutCompany: 'Buffer is a fully remote, bootstrapped social media management platform.',
    experience: '2+ years',
    companySize: '80 – 120 employees',
    companyWebsite: 'https://buffer.com',
    applicants: 44,
    responsibilities: [
      'Write SEO-optimised blog posts and long-form guides.',
      "Manage and grow Buffer's newsletter (80k+ subscribers).",
    ],
    requirements: ['2+ years of content marketing experience.', 'Excellent writing skills.'],
    niceToHave: ['Experience growing an email newsletter.'],
    benefits: ['100% remote — async-first team.', '4 weeks PTO plus paid holidays.'],
  },
  {
    title: 'iOS Developer',
    company: 'Duolingo',
    logo: '/icons/FeaturedJobs/Company Logo-2.svg',
    location: 'Toronto, Canada',
    type: 'Full Time',
    category: 'Engineering',
    salary: 'CA$110k – CA$140k',
    postedAt: '2 days ago',
    description: "Duolingo is building the future of education. Join us as an iOS Developer.",
    tags: ['Swift', 'iOS', 'Xcode'],
    featured: false,
    aboutCompany: 'Duolingo is the world\'s most popular language learning platform, with over 500 million learners.',
    experience: '3+ years',
    companySize: '700 – 1,000 employees',
    companyWebsite: 'https://duolingo.com',
    applicants: 136,
    responsibilities: [
      'Build and maintain high-quality iOS application features in Swift.',
      'Optimize app performance, memory, and battery usage.',
    ],
    requirements: ['3+ years of iOS development experience.', 'Proficiency in Swift and UIKit or SwiftUI.'],
    niceToHave: ['Experience with gamification or animation-heavy apps.'],
    benefits: ['Competitive salary + stock options.', 'Generous parental leave (18 weeks).'],
  },
  {
    title: 'HR Business Partner',
    company: 'Atlassian',
    logo: '/icons/FeaturedJobs/Company Logo-3.svg',
    location: 'Sydney, Australia',
    type: 'Full Time',
    category: 'Human Resource',
    salary: 'AU$95k – AU$120k',
    postedAt: '3 days ago',
    description: "Atlassian is looking for an HR Business Partner to drive talent strategy.",
    tags: ['HR', 'People Ops', 'Talent'],
    featured: false,
    aboutCompany: 'Atlassian makes tools like Jira, Confluence, and Trello used by 300,000+ customers.',
    experience: '5+ years',
    companySize: '10,000+ employees',
    companyWebsite: 'https://atlassian.com',
    applicants: 59,
    responsibilities: [
      'Partner with engineering leaders on org design and performance.',
      'Drive end-to-end performance review cycles.',
    ],
    requirements: [
      '5+ years of HRBP or people partner experience.',
      'Experience supporting large engineering organisations.',
    ],
    niceToHave: ['Experience in high-growth tech companies.'],
    benefits: ['Distributed-first, flexible work model.', 'Paid volunteer days (5 per year).'],
  },
  {
    title: 'Business Development Manager',
    company: 'Stripe',
    logo: '/icons/FeaturedJobs/Company Logo-4.svg',
    location: 'Singapore',
    type: 'Full Time',
    category: 'Business',
    salary: '$85k – $110k',
    postedAt: '4 days ago',
    description: "Stripe is expanding into Southeast Asia. As a BDM, you'll grow our regional revenue.",
    tags: ['Business', 'Partnerships', 'Strategy'],
    featured: false,
    aboutCompany: 'Stripe is a financial infrastructure platform for businesses.',
    experience: '4+ years',
    companySize: '4,000 – 6,000 employees',
    companyWebsite: 'https://stripe.com',
    applicants: 72,
    responsibilities: [
      'Identify and evaluate strategic partnership opportunities across SEA.',
      'Negotiate and close partnership agreements.',
    ],
    requirements: [
      '4+ years in business development or partnerships.',
      'Strong network in the Southeast Asia tech ecosystem.',
    ],
    niceToHave: ['Background in payments or fintech.'],
    benefits: ['Competitive package with equity.', 'Annual learning stipend.'],
  },
  {
    title: 'Full Stack Developer',
    company: 'Linear',
    logo: '/icons/FeaturedJobs/Company Logo-5.svg',
    location: 'Remote',
    type: 'Remote',
    category: 'Engineering',
    salary: '$105k – $140k',
    postedAt: '1 week ago',
    description: "Linear is hiring a Full Stack Developer to help build the fastest project management tool.",
    tags: ['TypeScript', 'React', 'GraphQL'],
    featured: true,
    aboutCompany: 'Linear builds software for high-performance teams.',
    experience: '4+ years',
    companySize: '40 – 80 employees',
    companyWebsite: 'https://linear.app',
    applicants: 175,
    responsibilities: [
      'Build product features across the React frontend and Node.js backend.',
      'Design and maintain GraphQL APIs.',
    ],
    requirements: [
      '4+ years of full-stack experience with TypeScript.',
      'Strong React skills and knowledge of modern state management.',
    ],
    niceToHave: ['Experience with real-time collaboration features.'],
    benefits: ['Fully remote team.', 'Equity with meaningful upside.'],
  },
  {
    title: 'Account Executive',
    company: 'Salesforce',
    logo: '/icons/FeaturedJobs/Company Logo-6.svg',
    location: 'New York, US',
    type: 'Full Time',
    category: 'Sales',
    salary: '$80k – $100k + commission',
    postedAt: '2 days ago',
    description: "Salesforce is looking for an AE to manage enterprise accounts and close complex deals.",
    tags: ['Sales', 'B2B', 'Enterprise'],
    featured: false,
    aboutCompany: 'Salesforce is the world\'s #1 CRM.',
    experience: '3+ years',
    companySize: '70,000+ employees',
    companyWebsite: 'https://salesforce.com',
    applicants: 203,
    responsibilities: [
      'Manage a portfolio of 20–30 enterprise accounts.',
      'Drive new logo acquisition and expand existing accounts.',
    ],
    requirements: [
      '3+ years of enterprise SaaS sales experience.',
      'Consistent track record of exceeding quota.',
    ],
    niceToHave: ['Experience selling Salesforce products.'],
    benefits: ['Base + uncapped commission (OTE $180k–$220k).', 'Top performer club trips.'],
  },
  {
    title: 'Motion Designer',
    company: 'Canva',
    logo: '/icons/FeaturedJobs/Company Logo.svg',
    location: 'Sydney, Australia',
    type: 'Full Time',
    category: 'Design',
    salary: 'AU$80k – AU$110k',
    postedAt: '6 days ago',
    description: "Canva needs a Motion Designer to bring our product and brand to life through animation.",
    tags: ['Motion', 'After Effects', 'Design'],
    featured: false,
    aboutCompany: 'Canva is a global design platform with 170+ million monthly active users.',
    experience: '3+ years',
    companySize: '3,000 – 4,000 employees',
    companyWebsite: 'https://canva.com',
    applicants: 82,
    responsibilities: [
      'Create high-impact animations and motion graphics for product and marketing.',
      'Design video ads, social media animations, and launch videos.',
    ],
    requirements: [
      '3+ years of motion design experience.',
      'Advanced skills in After Effects, Premiere Pro, and Cinema 4D.',
    ],
    niceToHave: ['Experience with Lottie/JSON animations for web.'],
    benefits: ['Equity (Canva is pre-IPO!).', 'Annual Vibe & Thrive allowance (AU$1,000).'],
  },
  {
    title: 'Machine Learning Engineer',
    company: 'OpenAI',
    logo: '/icons/FeaturedJobs/Dropbox.svg',
    location: 'San Francisco, US',
    type: 'Full Time',
    category: 'Technology',
    salary: '$180k – $250k',
    postedAt: '1 day ago',
    description: "OpenAI is hiring ML Engineers to train and fine-tune large language models.",
    tags: ['ML', 'Python', 'PyTorch'],
    featured: true,
    aboutCompany: 'OpenAI is an AI safety company and the creator of ChatGPT, GPT-4, DALL-E, and Whisper.',
    experience: '5+ years',
    companySize: '700 – 1,000 employees',
    companyWebsite: 'https://openai.com',
    applicants: 519,
    responsibilities: [
      'Design and implement training pipelines for large language models.',
      'Run large-scale distributed training experiments on GPU clusters.',
    ],
    requirements: [
      '5+ years of ML engineering or applied research experience.',
      'Deep expertise in PyTorch and large-scale distributed training.',
    ],
    niceToHave: ['Publications in NeurIPS, ICML, ICLR, or similar venues.'],
    benefits: ['Industry-leading compensation package.', 'Significant equity stake.'],
  },
  {
    title: 'Product Manager',
    company: 'Intercom',
    logo: '/icons/FeaturedJobs/Company Logo-1.svg',
    location: 'London, UK',
    type: 'Full Time',
    category: 'Business',
    salary: '£70k – £95k',
    postedAt: '3 days ago',
    description: "Intercom is looking for a PM to own the roadmap for our AI-powered customer support platform.",
    tags: ['Product', 'Roadmap', 'Strategy'],
    featured: false,
    aboutCompany: 'Intercom is the complete AI-first customer service solution.',
    experience: '4+ years',
    companySize: '900 – 1,200 employees',
    companyWebsite: 'https://intercom.com',
    applicants: 98,
    responsibilities: [
      'Own the product roadmap for a key area of the Intercom platform.',
      'Define product strategy, prioritisation, and success metrics.',
    ],
    requirements: [
      '4+ years of product management experience in B2B SaaS.',
      'Strong analytical skills and data-driven decision making.',
    ],
    niceToHave: ['Experience with AI/ML product features.'],
    benefits: ['Competitive salary and equity.', '16 weeks paid parental leave.'],
  },
  {
    title: 'Cybersecurity Analyst',
    company: 'CrowdStrike',
    logo: '/icons/FeaturedJobs/Company Logo-2.svg',
    location: 'Madrid, Spain',
    type: 'Full Time',
    category: 'Technology',
    salary: '€60k – €80k',
    postedAt: '5 days ago',
    description: "CrowdStrike is seeking a Cybersecurity Analyst to monitor threats and investigate incidents.",
    tags: ['Security', 'SIEM', 'SOC'],
    featured: false,
    aboutCompany: 'CrowdStrike is a global cybersecurity leader protecting critical enterprise infrastructure.',
    experience: '2+ years',
    companySize: '8,000+ employees',
    companyWebsite: 'https://crowdstrike.com',
    applicants: 67,
    responsibilities: [
      'Monitor security alerts and investigate potential incidents using Falcon.',
      'Perform threat hunting and anomaly detection.',
    ],
    requirements: [
      '2+ years in a SOC analyst or equivalent cybersecurity role.',
      'Hands-on experience with SIEM tools.',
    ],
    niceToHave: ['Experience with the CrowdStrike Falcon platform.'],
    benefits: ['Competitive base salary.', 'Remote work flexibility.'],
  },
  {
    title: 'Marketing Intern',
    company: 'Notion',
    logo: '/icons/FeaturedJobs/Company Logo-3.svg',
    location: 'Berlin, Germany',
    type: 'Internship',
    category: 'Marketing',
    salary: '€18/hr',
    postedAt: '2 days ago',
    description: "Notion is looking for a Marketing Intern to support campaign execution across Europe.",
    tags: ['Marketing', 'Social Media', 'Intern'],
    featured: false,
    aboutCompany: 'Notion is on a mission to make it possible for every person and company to tailor their tools.',
    experience: '0–1 year',
    companySize: '500 – 800 employees',
    companyWebsite: 'https://notion.so',
    applicants: 211,
    responsibilities: [
      'Support the marketing team in executing regional campaigns.',
      "Manage Notion's social media accounts for the DACH region.",
    ],
    requirements: [
      "Currently enrolled in a bachelor's or master's programme.",
      'Strong written and verbal communication skills in English and German.',
    ],
    niceToHave: ['Experience with Notion (personal or professional).'],
    benefits: ['Competitive intern hourly rate (€18/hr).', 'Real responsibility from day one.'],
  },
  {
    title: 'Talent Acquisition Specialist',
    company: 'Shopify',
    logo: '/icons/FeaturedJobs/Company Logo-4.svg',
    location: 'Toronto, Canada',
    type: 'Full Time',
    category: 'Human Resource',
    salary: 'CA$70k – CA$90k',
    postedAt: '4 days ago',
    description: "Shopify's recruitment team is growing! Join us as a Talent Acquisition Specialist.",
    tags: ['HR', 'Recruiting', 'Talent'],
    featured: false,
    aboutCompany: 'Shopify provides essential internet infrastructure for commerce.',
    experience: '2+ years',
    companySize: '10,000+ employees',
    companyWebsite: 'https://shopify.com',
    applicants: 85,
    responsibilities: [
      'Own end-to-end recruiting for technical roles.',
      'Build and maintain talent pipelines through proactive sourcing.',
    ],
    requirements: [
      '2+ years of technical recruiting experience.',
      'Familiarity with LinkedIn Recruiter sourcing techniques.',
    ],
    niceToHave: ['Experience recruiting globally across multiple time zones.'],
    benefits: ['Digital by default — fully remote.', 'Equity (RSUs).'],
  },
  {
    title: 'Cloud Architect',
    company: 'AWS',
    logo: '/icons/FeaturedJobs/Company Logo-5.svg',
    location: 'New York, US',
    type: 'Contract',
    category: 'Engineering',
    salary: '$150/hr – $200/hr',
    postedAt: '1 week ago',
    description: "AWS is looking for a Cloud Architect on contract to design enterprise-scale cloud migrations.",
    tags: ['AWS', 'Architecture', 'Cloud'],
    featured: false,
    aboutCompany: 'Amazon Web Services (AWS) is the world\'s most comprehensive cloud platform.',
    experience: '8+ years',
    companySize: '100,000+ employees',
    companyWebsite: 'https://aws.amazon.com',
    applicants: 41,
    responsibilities: [
      'Lead cloud migration assessments and architecture workshops.',
      'Design multi-account AWS landing zones using best-practice security controls.',
    ],
    requirements: [
      '8+ years of cloud architecture or infrastructure experience.',
      'AWS Solutions Architect Professional certification required.',
    ],
    niceToHave: ['AWS Security or Database Specialty certifications.'],
    benefits: ['Premium contract rate ($150–$200/hr).', 'Travel and expenses covered.'],
  },
  {
    title: 'Finance Controller',
    company: 'Revolut',
    logo: '/icons/FeaturedJobs/Company Logo-6.svg',
    location: 'London, UK',
    type: 'Full Time',
    category: 'Finance',
    salary: '£80k – £100k',
    postedAt: '3 days ago',
    description: "Revolut is hiring a Finance Controller to oversee month-end close and regulatory reporting.",
    tags: ['Finance', 'Accounting', 'Reporting'],
    featured: false,
    aboutCompany: 'Revolut is a fintech super-app with 35+ million customers globally.',
    experience: '5+ years',
    companySize: '6,000+ employees',
    companyWebsite: 'https://revolut.com',
    applicants: 57,
    responsibilities: [
      'Manage month-end, quarter-end, and year-end close processes.',
      'Produce consolidated financial statements across 20+ global entities.',
    ],
    requirements: [
      '5+ years in a finance controller or senior accountant role.',
      'ACA, ACCA, or CIMA qualified.',
    ],
    niceToHave: ['Experience in fintech, banking, or regulated financial services.'],
    benefits: ['Competitive salary and bonus.', 'Revolut Premium account.'],
  },
];

const seed = async () => {
  await connectDB();

  try {
    await Job.deleteMany({});
    console.log('Existing jobs cleared.');

    const inserted = await Job.insertMany(jobs);
    console.log(`✓ Seeded ${inserted.length} jobs successfully.`);

    // ── Admin account ──────────────────────────────────────────────────────
    await User.deleteOne({ email: 'admin' });
    await User.create({
      name: 'Admin',
      email: 'admin',
      password: 'admin123',
      role: 'admin',
    });
    console.log('✓ Admin account ready: admin / admin123');

    // ── User account ───────────────────────────────────────────────────────
    await User.deleteOne({ email: 'user' });
    await User.create({
      name: 'User',
      email: 'user',
      password: 'user123',
      role: 'user',
    });
    console.log('✓ User account ready:  user  / user123');
    // ───────────────────────────────────────────────────────────────────────
  } catch (error) {
    console.error('Seed error:', error.message);
  } finally {
    await mongoose.connection.close();
    console.log('MongoDB connection closed.');
    process.exit(0);
  }
};

seed();
