export interface JobDetail {
  aboutCompany: string;
  experience: string;
  companySize: string;
  companyWebsite: string;
  applicants: number;
  responsibilities: string[];
  requirements: string[];
  niceToHave: string[];
  benefits: string[];
}

export interface Job extends Partial<JobDetail> {
  id: number;
  title: string;
  company: string;
  logo: string;
  location: string;
  type: "Full Time" | "Part Time" | "Remote" | "Contract" | "Internship";
  category: string;
  salary: string;
  postedAt: string;
  description: string;
  tags: string[];
  featured?: boolean;
}

export const JOB_CATEGORIES = [
  "All",
  "Design",
  "Engineering",
  "Marketing",
  "Finance",
  "Technology",
  "Sales",
  "Business",
  "Human Resource",
];

export const JOB_LOCATIONS = [
  "All",
  "Remote",
  "New York, US",
  "San Francisco, US",
  "London, UK",
  "Berlin, Germany",
  "Madrid, Spain",
  "Toronto, Canada",
  "Sydney, Australia",
  "Singapore",
];

export const JOB_TYPES = [
  "All",
  "Full Time",
  "Part Time",
  "Remote",
  "Contract",
  "Internship",
];

export const dummyJobs: Job[] = [
  {
    id: 1,
    title: "Senior Product Designer",
    company: "Stripe",
    logo: "/icons/FeaturedJobs/Company Logo.svg",
    location: "San Francisco, US",
    type: "Full Time",
    category: "Design",
    salary: "$90k – $120k",
    postedAt: "2 days ago",
    description:
      "Stripe is looking for a Senior Product Designer to craft elegant, user-centered interfaces across our payments platform. You'll work closely with engineering and product teams.",
    tags: ["Design", "Figma", "UI/UX"],
    featured: true,
  },
  {
    id: 2,
    title: "Frontend Engineer",
    company: "Vercel",
    logo: "/icons/FeaturedJobs/Dropbox.svg",
    location: "Remote",
    type: "Remote",
    category: "Engineering",
    salary: "$110k – $150k",
    postedAt: "1 day ago",
    description:
      "Join Vercel's product team as a Frontend Engineer. You'll be building blazing fast web experiences using Next.js, React, and TypeScript.",
    tags: ["React", "TypeScript", "Next.js"],
    featured: true,
  },
  {
    id: 3,
    title: "Growth Marketing Manager",
    company: "Revolut",
    logo: "/icons/FeaturedJobs/Company Logo-1.svg",
    location: "London, UK",
    type: "Full Time",
    category: "Marketing",
    salary: "£70k – £90k",
    postedAt: "3 days ago",
    description:
      "Revolut is seeking a data-driven Growth Marketing Manager to lead user acquisition campaigns across paid, organic, and referral channels globally.",
    tags: ["Marketing", "Growth", "Analytics"],
    featured: false,
  },
  {
    id: 4,
    title: "Data Scientist",
    company: "Spotify",
    logo: "/icons/FeaturedJobs/Company Logo-2.svg",
    location: "New York, US",
    type: "Full Time",
    category: "Technology",
    salary: "$130k – $170k",
    postedAt: "5 days ago",
    description:
      "Spotify's data team is hiring a Data Scientist to build models that power music recommendations for over 400 million users worldwide.",
    tags: ["Python", "ML", "Data"],
    featured: true,
  },
  {
    id: 5,
    title: "Brand Designer",
    company: "Dropbox",
    logo: "/icons/FeaturedJobs/Company Logo-3.svg",
    location: "San Francisco, US",
    type: "Full Time",
    category: "Design",
    salary: "$80k – $105k",
    postedAt: "1 week ago",
    description:
      "Dropbox is looking for a Brand Designer to evolve and extend our visual identity across marketing materials, product launching, and more.",
    tags: ["Design", "Branding", "Illustration"],
    featured: false,
  },
  {
    id: 6,
    title: "Backend Engineer",
    company: "Notion",
    logo: "/icons/FeaturedJobs/Company Logo-4.svg",
    location: "Remote",
    type: "Remote",
    category: "Engineering",
    salary: "$120k – $160k",
    postedAt: "4 days ago",
    description:
      "Notion is hiring a Backend Engineer to design and build scalable APIs that power our all-in-one productivity tool used by millions of teams.",
    tags: ["Node.js", "PostgreSQL", "API"],
    featured: false,
  },
  {
    id: 7,
    title: "Financial Analyst",
    company: "Airbnb",
    logo: "/icons/FeaturedJobs/Company Logo-5.svg",
    location: "New York, US",
    type: "Full Time",
    category: "Finance",
    salary: "$95k – $125k",
    postedAt: "2 days ago",
    description:
      "Airbnb's finance team is seeking a sharp Financial Analyst to support FP&A, budgeting, and strategic financial planning across the business.",
    tags: ["Finance", "Excel", "FP&A"],
    featured: false,
  },
  {
    id: 8,
    title: "Sales Development Representative",
    company: "HubSpot",
    logo: "/icons/FeaturedJobs/Company Logo-6.svg",
    location: "Berlin, Germany",
    type: "Full Time",
    category: "Sales",
    salary: "€45k – €65k",
    postedAt: "6 days ago",
    description:
      "HubSpot is growing its European sales team. As an SDR, you'll prospect and qualify outbound leads, driving pipeline for our account executives.",
    tags: ["Sales", "CRM", "Outbound"],
    featured: false,
  },
  {
    id: 9,
    title: "DevOps Engineer",
    company: "Hashicorp",
    logo: "/icons/FeaturedJobs/Company Logo.svg",
    location: "Remote",
    type: "Remote",
    category: "Engineering",
    salary: "$115k – $145k",
    postedAt: "3 days ago",
    description:
      "HashiCorp is looking for a DevOps Engineer to maintain and scale our cloud infrastructure using Terraform, Vault, and Kubernetes.",
    tags: ["Kubernetes", "Terraform", "AWS"],
    featured: false,
  },
  {
    id: 10,
    title: "UX Researcher",
    company: "Figma",
    logo: "/icons/FeaturedJobs/Dropbox.svg",
    location: "San Francisco, US",
    type: "Full Time",
    category: "Design",
    salary: "$100k – $130k",
    postedAt: "1 week ago",
    description:
      "Figma is searching for a UX Researcher to conduct usability studies, user interviews, and synthesise insights that shape our collaborative design tool.",
    tags: ["Research", "UX", "User Testing"],
    featured: true,
  },
  {
    id: 11,
    title: "Content Marketing Specialist",
    company: "Buffer",
    logo: "/icons/FeaturedJobs/Company Logo-1.svg",
    location: "Remote",
    type: "Remote",
    category: "Marketing",
    salary: "$60k – $80k",
    postedAt: "5 days ago",
    description:
      "Buffer is hiring a Content Marketing Specialist to write blog posts, newsletters, and social content that grows our audience organically.",
    tags: ["Content", "SEO", "Writing"],
    featured: false,
  },
  {
    id: 12,
    title: "iOS Developer",
    company: "Duolingo",
    logo: "/icons/FeaturedJobs/Company Logo-2.svg",
    location: "Toronto, Canada",
    type: "Full Time",
    category: "Engineering",
    salary: "CA$110k – CA$140k",
    postedAt: "2 days ago",
    description:
      "Duolingo is building the future of education. Join us as an iOS Developer to craft delightful, gamified language learning experiences for millions of learners.",
    tags: ["Swift", "iOS", "Xcode"],
    featured: false,
  },
  {
    id: 13,
    title: "HR Business Partner",
    company: "Atlassian",
    logo: "/icons/FeaturedJobs/Company Logo-3.svg",
    location: "Sydney, Australia",
    type: "Full Time",
    category: "Human Resource",
    salary: "AU$95k – AU$120k",
    postedAt: "3 days ago",
    description:
      "Atlassian is looking for an HR Business Partner to drive talent strategy, performance management, and culture programs across our engineering org.",
    tags: ["HR", "People Ops", "Talent"],
    featured: false,
  },
  {
    id: 14,
    title: "Business Development Manager",
    company: "Stripe",
    logo: "/icons/FeaturedJobs/Company Logo-4.svg",
    location: "Singapore",
    type: "Full Time",
    category: "Business",
    salary: "$85k – $110k",
    postedAt: "4 days ago",
    description:
      "Stripe is expanding into Southeast Asia. As a Business Development Manager, you'll identify partners, negotiate deals, and grow our regional revenue.",
    tags: ["Business", "Partnerships", "Strategy"],
    featured: false,
  },
  {
    id: 15,
    title: "Full Stack Developer",
    company: "Linear",
    logo: "/icons/FeaturedJobs/Company Logo-5.svg",
    location: "Remote",
    type: "Remote",
    category: "Engineering",
    salary: "$105k – $140k",
    postedAt: "1 week ago",
    description:
      "Linear is hiring a Full Stack Developer to help build the fastest project management tool in the industry. Work with TypeScript, React, and GraphQL.",
    tags: ["TypeScript", "React", "GraphQL"],
    featured: true,
  },
  {
    id: 16,
    title: "Account Executive",
    company: "Salesforce",
    logo: "/icons/FeaturedJobs/Company Logo-6.svg",
    location: "New York, US",
    type: "Full Time",
    category: "Sales",
    salary: "$80k – $100k + commission",
    postedAt: "2 days ago",
    description:
      "Salesforce is looking for an AE to manage enterprise accounts, close complex deals, and build long-term relationships with Fortune 500 clients.",
    tags: ["Sales", "B2B", "Enterprise"],
    featured: false,
  },
  {
    id: 17,
    title: "Motion Designer",
    company: "Canva",
    logo: "/icons/FeaturedJobs/Company Logo.svg",
    location: "Sydney, Australia",
    type: "Full Time",
    category: "Design",
    salary: "AU$80k – AU$110k",
    postedAt: "6 days ago",
    description:
      "Canva needs a Motion Designer to bring our product and brand to life through animation, video, and interactive digital experiences.",
    tags: ["Motion", "After Effects", "Design"],
    featured: false,
  },
  {
    id: 18,
    title: "Machine Learning Engineer",
    company: "OpenAI",
    logo: "/icons/FeaturedJobs/Dropbox.svg",
    location: "San Francisco, US",
    type: "Full Time",
    category: "Technology",
    salary: "$180k – $250k",
    postedAt: "1 day ago",
    description:
      "OpenAI is hiring ML Engineers to train and fine-tune large language models, working at the cutting edge of AI research and product deployment.",
    tags: ["ML", "Python", "PyTorch"],
    featured: true,
  },
  {
    id: 19,
    title: "Product Manager",
    company: "Intercom",
    logo: "/icons/FeaturedJobs/Company Logo-1.svg",
    location: "London, UK",
    type: "Full Time",
    category: "Business",
    salary: "£70k – £95k",
    postedAt: "3 days ago",
    description:
      "Intercom is looking for a PM to own the roadmap for our AI-powered customer support platform, collaborating cross-functionally with design and engineering.",
    tags: ["Product", "Roadmap", "Strategy"],
    featured: false,
  },
  {
    id: 20,
    title: "Cybersecurity Analyst",
    company: "CrowdStrike",
    logo: "/icons/FeaturedJobs/Company Logo-2.svg",
    location: "Madrid, Spain",
    type: "Full Time",
    category: "Technology",
    salary: "€60k – €80k",
    postedAt: "5 days ago",
    description:
      "CrowdStrike is seeking a Cybersecurity Analyst to monitor threats, investigate incidents, and strengthen our clients' security posture using Falcon.",
    tags: ["Security", "SIEM", "SOC"],
    featured: false,
  },
  {
    id: 21,
    title: "Marketing Intern",
    company: "Notion",
    logo: "/icons/FeaturedJobs/Company Logo-3.svg",
    location: "Berlin, Germany",
    type: "Internship",
    category: "Marketing",
    salary: "€18/hr",
    postedAt: "2 days ago",
    description:
      "Notion is looking for a Marketing Intern to support campaign execution, community initiatives, and brand storytelling across Europe.",
    tags: ["Marketing", "Social Media", "Intern"],
    featured: false,
  },
  {
    id: 22,
    title: "Talent Acquisition Specialist",
    company: "Shopify",
    logo: "/icons/FeaturedJobs/Company Logo-4.svg",
    location: "Toronto, Canada",
    type: "Full Time",
    category: "Human Resource",
    salary: "CA$70k – CA$90k",
    postedAt: "4 days ago",
    description:
      "Shopify's recruitment team is growing! Join us as a Talent Acquisition Specialist to source, attract, and hire top engineering talent globally.",
    tags: ["HR", "Recruiting", "Talent"],
    featured: false,
  },
  {
    id: 23,
    title: "Cloud Architect",
    company: "AWS",
    logo: "/icons/FeaturedJobs/Company Logo-5.svg",
    location: "New York, US",
    type: "Contract",
    category: "Engineering",
    salary: "$150/hr – $200/hr",
    postedAt: "1 week ago",
    description:
      "AWS is looking for a Cloud Architect on contract to design and implement enterprise-scale cloud migrations and infrastructure solutions.",
    tags: ["AWS", "Architecture", "Cloud"],
    featured: false,
  },
  {
    id: 24,
    title: "Finance Controller",
    company: "Revolut",
    logo: "/icons/FeaturedJobs/Company Logo-6.svg",
    location: "London, UK",
    type: "Full Time",
    category: "Finance",
    salary: "£80k – £100k",
    postedAt: "3 days ago",
    description:
      "Revolut is hiring a Finance Controller to oversee month-end close, manage regulatory reporting, and ensure financial accuracy across global entities.",
    tags: ["Finance", "Accounting", "Reporting"],
    featured: false,
  },
];

export const jobDetails: Record<number, JobDetail> = {
  1: {
    aboutCompany:
      "Stripe is a financial infrastructure platform for businesses. Millions of companies—from the world's largest enterprises to the most ambitious startups—use Stripe to accept payments, grow their revenue, and accelerate new business opportunities.",
    experience: "4+ years",
    companySize: "4,000 – 6,000 employees",
    companyWebsite: "https://stripe.com",
    applicants: 148,
    responsibilities: [
      "Design end-to-end user experiences across web and mobile products.",
      "Collaborate with engineers and PMs to deliver polished, pixel-perfect interfaces.",
      "Conduct user research and usability testing to validate design decisions.",
      "Create and maintain design system components in Figma.",
      "Present design concepts to stakeholders and incorporate feedback effectively.",
    ],
    requirements: [
      "4+ years of product design experience at a tech company.",
      "Strong portfolio demonstrating UI/UX problem-solving.",
      "Proficiency in Figma and prototyping tools.",
      "Experience designing complex B2B or fintech products.",
      "Excellent communication and collaboration skills.",
    ],
    niceToHave: [
      "Experience with motion design or micro-interactions.",
      "Familiarity with front-end technologies (HTML, CSS, React).",
      "Prior experience working in a fintech or payments company.",
    ],
    benefits: [
      "Comprehensive health, dental & vision insurance.",
      "Generous equity package.",
      "Flexible remote work policy.",
      "Annual learning & development stipend ($2,000).",
      "Home office setup budget.",
      "Unlimited PTO with a recommended minimum.",
    ],
  },
  2: {
    aboutCompany:
      "Vercel is the platform for frontend developers, providing the speed and reliability innovators need to create at the moment of inspiration. We enable teams to iterate quickly and develop, preview, and ship delightful user experiences.",
    experience: "3+ years",
    companySize: "500 – 1,000 employees",
    companyWebsite: "https://vercel.com",
    applicants: 231,
    responsibilities: [
      "Build and maintain high-performance UI components in React and TypeScript.",
      "Contribute to open-source Next.js projects and internal tooling.",
      "Optimize for performance, accessibility, and developer experience.",
      "Collaborate with design and backend teams in an async-first environment.",
      "Write thorough tests and documentation for all production code.",
    ],
    requirements: [
      "3+ years of frontend engineering experience.",
      "Deep knowledge of React, TypeScript, and modern CSS.",
      "Familiarity with Next.js and Edge runtime concepts.",
      "Strong understanding of web performance and Core Web Vitals.",
      "Experience with CI/CD pipelines and deployment workflows.",
    ],
    niceToHave: [
      "Contributions to open-source projects.",
      "Experience with Turbopack or Webpack internals.",
      "Knowledge of WebAssembly.",
    ],
    benefits: [
      "100% remote — work from anywhere in the world.",
      "Competitive salary + meaningful equity.",
      "Top-tier health, dental, and vision coverage.",
      "$500/month stipend for remote work setup.",
      "Annual team retreats.",
      "Generous parental leave policy.",
    ],
  },
  3: {
    aboutCompany:
      "Revolut is a fintech super-app with 35+ million customers globally. We offer banking, trading, crypto, and payments services — and we're on a mission to build the world's first truly global financial super-app.",
    experience: "3+ years",
    companySize: "6,000+ employees",
    companyWebsite: "https://revolut.com",
    applicants: 94,
    responsibilities: [
      "Own and scale paid acquisition channels (Google, Meta, TikTok).",
      "Develop referral and lifecycle marketing programs to boost LTV.",
      "Analyse funnel performance and translate insights into growth experiments.",
      "Collaborate with design, data, and product teams on campaign execution.",
      "Report on key growth metrics to senior leadership weekly.",
    ],
    requirements: [
      "3+ years in growth or performance marketing.",
      "Hands-on experience managing large-scale paid ad budgets.",
      "Strong analytical skills — comfortable with SQL and BI tools.",
      "Experience running A/B tests and multivariate experiments.",
      "Excellent written and verbal communication skills.",
    ],
    niceToHave: [
      "Experience in fintech or subscription businesses.",
      "Knowledge of attribution modelling (MMM, MTA).",
      "Familiarity with Braze or Iterable for lifecycle campaigns.",
    ],
    benefits: [
      "Competitive salary + performance bonus.",
      "Revolut premium account on us.",
      "Flexible hybrid working (2 days in-office).",
      "Private health insurance.",
      "Generous learning budget.",
      "Global team retreats twice a year.",
    ],
  },
  4: {
    aboutCompany:
      "Spotify is the world's most popular audio streaming subscription service with 600 million users and 240 million subscribers across 180+ markets. Our mission is to unlock the potential of human creativity.",
    experience: "5+ years",
    companySize: "9,000+ employees",
    companyWebsite: "https://spotify.com",
    applicants: 312,
    responsibilities: [
      "Build and evaluate recommendation models at scale for 400M+ users.",
      "Collaborate with ML engineers to deploy models into production.",
      "Perform exploratory data analysis to identify patterns and insights.",
      "Design and analyse A/B experiments to measure model impact.",
      "Present data-driven findings to non-technical stakeholders.",
    ],
    requirements: [
      "5+ years of data science or ML experience.",
      "Proficiency in Python (pandas, scikit-learn, PyTorch or TensorFlow).",
      "Strong statistics foundations and experimental design knowledge.",
      "Experience working with large-scale data pipelines (Spark, Databricks).",
      "MS or PhD in a quantitative field preferred.",
    ],
    niceToHave: [
      "Experience with audio ML or NLP.",
      "Publications in top ML conferences (NeurIPS, ICML, etc.).",
      "Knowledge of causal inference methods.",
    ],
    benefits: [
      "Spotify Premium subscription for you and a family member.",
      "Stock options with a 4-year vesting schedule.",
      "Flexible work from home policy.",
      "Monthly wellness allowance.",
      "Generous parental leave (6 months fully paid).",
      "Annual conference and training budget.",
    ],
  },
  5: {
    aboutCompany:
      "Dropbox is the world's first smart workspace that helps people and teams focus on the work that matters. With more than 700 million registered users across 180+ countries, Dropbox has billions of files across its platform.",
    experience: "3+ years",
    companySize: "2,500 – 3,000 employees",
    companyWebsite: "https://dropbox.com",
    applicants: 76,
    responsibilities: [
      "Create compelling visual assets for marketing campaigns across digital and print.",
      "Extend and maintain Dropbox's brand identity guidelines.",
      "Design for product launches, social media, and events.",
      "Collaborate with marketing leads and external agencies.",
      "Ensure brand consistency across all customer-facing touchpoints.",
    ],
    requirements: [
      "3+ years of brand or graphic design experience.",
      "Strong portfolio with diverse brand/identity work.",
      "Mastery of Adobe Creative Suite and Figma.",
      "Experience working within and evolving established brand systems.",
      "Ability to manage multiple projects and meet tight deadlines.",
    ],
    niceToHave: [
      "Motion design or video editing skills.",
      "Experience with 3D design tools (Cinema 4D, Spline).",
      "Background in illustration.",
    ],
    benefits: [
      "Virtual-first work culture — work from anywhere.",
      "Comprehensive medical, dental, and vision.",
      "Equity grants refreshed annually.",
      "$2,000 laptop and equipment allowance.",
      "Mental health and wellness support.",
      "14 weeks fully paid parental leave.",
    ],
  },
  6: {
    aboutCompany:
      "Notion is on a mission to make it possible for every person and company to tailor their tools to their needs. We create a more connected and customisable workspace, used by teams at companies like Nike, Figma, and Pixar.",
    experience: "4+ years",
    companySize: "500 – 800 employees",
    companyWebsite: "https://notion.so",
    applicants: 189,
    responsibilities: [
      "Design, build, and maintain highly available RESTful and GraphQL APIs.",
      "Own and improve database performance for PostgreSQL at scale.",
      "Collaborate with product and frontend teams to ship new features.",
      "Contribute to backend architecture decisions and technical roadmap.",
      "Mentor junior engineers and lead code reviews.",
    ],
    requirements: [
      "4+ years of backend engineering experience.",
      "Strong proficiency in Node.js or TypeScript.",
      "Deep understanding of relational databases and query optimisation.",
      "Experience with distributed systems and microservices.",
      "Solid understanding of REST and GraphQL API design.",
    ],
    niceToHave: [
      "Experience with real-time collaboration systems (OT/CRDTs).",
      "Familiarity with Kubernetes and GCP.",
      "Open-source contributions.",
    ],
    benefits: [
      "Competitive salary and equity package.",
      "Fully remote — flexible schedule.",
      "Medical, dental, and vision for you and dependents.",
      "$1,000 home office setup stipend.",
      "Notion team plan (obviously!).",
      "Annual team off-sites.",
    ],
  },
  7: {
    aboutCompany:
      "Airbnb is a global travel community that offers magical end-to-end trips, including where you stay, what you do and the people you meet. With 5 million hosts and 1.5 billion guest arrivals, Airbnb is redefining how people experience travel.",
    experience: "2+ years",
    companySize: "6,000+ employees",
    companyWebsite: "https://airbnb.com",
    applicants: 62,
    responsibilities: [
      "Support monthly and quarterly financial close and reporting.",
      "Build and maintain financial models for budgeting and forecasting.",
      "Prepare board-level financial presentations and business reviews.",
      "Analyse variances between actuals and targets and explain drivers.",
      "Partner with business units to provide financial support and insights.",
    ],
    requirements: [
      "2+ years in FP&A, corporate finance, or investment banking.",
      "Advanced Excel and financial modelling skills.",
      "Experience with BI tools (Tableau, Looker, or Power BI).",
      "Strong written and verbal communication skills.",
      "Detail-oriented with the ability to synthesise complex financial data.",
    ],
    niceToHave: [
      "Experience with Anaplan or Workday Adaptive.",
      "CFA or CPA in progress or completed.",
      "Background in tech or marketplace businesses.",
    ],
    benefits: [
      "Annual travel credit for Airbnb bookings.",
      "Competitive base + annual bonus.",
      "Comprehensive benefits package.",
      "Employee stock purchase plan.",
      "Flexible hybrid work arrangement.",
      "Paid volunteer time off.",
    ],
  },
  8: {
    aboutCompany:
      "HubSpot is the customer platform that helps businesses grow better. With products for marketing, sales, service, and content management — all built on the same Smart CRM — HubSpot empowers over 228,000 customers in 135+ countries.",
    experience: "1+ year",
    companySize: "7,000+ employees",
    companyWebsite: "https://hubspot.com",
    applicants: 53,
    responsibilities: [
      "Research, identify, and prospect into target accounts via email, phone, and LinkedIn.",
      "Qualify inbound leads and schedule meetings for Account Executives.",
      "Maintain accurate pipeline data and notes in HubSpot CRM.",
      "Collaborate with marketing on outbound campaign messaging.",
      "Exceed monthly SQL and pipeline generation quotas.",
    ],
    requirements: [
      "1+ year in a sales or customer-facing role.",
      "Strong written English and German communication skills.",
      "Self-motivated with a competitive drive to exceed targets.",
      "Comfortable with rejection and handling objections.",
      "Experience using a CRM (HubSpot is a plus!).",
    ],
    niceToHave: [
      "Previous B2B SaaS SDR experience.",
      "Fluency in a third European language.",
      "Familiarity with sales engagement tools (Outreach, Salesloft).",
    ],
    benefits: [
      "Base salary + uncapped commission.",
      "Clear promotion path to AE within 12–18 months.",
      "Generous stock options.",
      "5 weeks paid vacation per year.",
      "Learning & development budget (€1,500/year).",
      "Mental health days and wellness programmes.",
    ],
  },
  9: {
    aboutCompany:
      "HashiCorp provides infrastructure automation software for multi-cloud environments, enabling enterprises to unlock a common cloud operating model. Teams use Terraform, Vault, Nomad, and Consul to provision, secure, and connect infrastructure.",
    experience: "4+ years",
    companySize: "1,500 – 2,500 employees",
    companyWebsite: "https://hashicorp.com",
    applicants: 107,
    responsibilities: [
      "Design and maintain CI/CD pipelines for production and staging environments.",
      "Manage Kubernetes clusters on AWS and GCP for reliability and scalability.",
      "Automate infrastructure provisioning using Terraform and Ansible.",
      "Monitor system health and respond to production incidents on-call.",
      "Champion DevOps best practices and internal platform improvements.",
    ],
    requirements: [
      "4+ years of DevOps or SRE experience.",
      "Deep expertise in Kubernetes and Docker.",
      "Strong Terraform and infrastructure-as-code skills.",
      "Experience with AWS (EC2, EKS, RDS, S3).",
      "Proficiency in Python or Bash scripting.",
    ],
    niceToHave: [
      "HashiCorp certifications (Terraform Associate, Vault Associate).",
      "Experience with Istio or service mesh architectures.",
      "Familiarity with Datadog or Prometheus/Grafana observability stacks.",
    ],
    benefits: [
      "Remote-first culture.",
      "Competitive salary and equity.",
      "Home office stipend ($1,200 one-time).",
      "Health, dental, and vision for you and family.",
      "Tech conference sponsorships.",
      "Paid parental leave (16 weeks).",
    ],
  },
  10: {
    aboutCompany:
      "Figma is a collaborative design tool built for the web. It's used by teams at Google, Airbnb, Spotify, and thousands of startups to design, prototype, and ship products faster together.",
    experience: "3+ years",
    companySize: "1,000 – 1,500 employees",
    companyWebsite: "https://figma.com",
    applicants: 88,
    responsibilities: [
      "Plan and conduct generative and evaluative user research studies.",
      "Synthesise qualitative and quantitative data into actionable insights.",
      "Advocate for the user in product roadmap discussions.",
      "Build and maintain a user research repository.",
      "Collaborate closely with designers, PMs, and engineers.",
    ],
    requirements: [
      "3+ years of UX research experience in a tech product environment.",
      "Expertise in research methods (interviews, surveys, usability tests, diary studies).",
      "Strong storytelling and data synthesis skills.",
      "Experience with tools like UserZoom, Maze, Dovetail, or Lookback.",
      "Ability to work cross-functionally and influence without authority.",
    ],
    niceToHave: [
      "Experience with quantitative research or data analysis (SQL, Python).",
      "Familiarity with design systems research.",
      "Background in cognitive psychology or HCI.",
    ],
    benefits: [
      "Figma Teams subscription (naturally!).",
      "Comprehensive medical, dental, and vision.",
      "Annual $2,500 learning and development budget.",
      "Flexible hybrid work model.",
      "Paid parental leave (18 weeks).",
      "Generous equity refresh programme.",
    ],
  },
  11: {
    aboutCompany:
      "Buffer is a fully remote, bootstrapped social media management platform. We're a team of about 80 people spread across the globe, building tools that help businesses grow their social presence.",
    experience: "2+ years",
    companySize: "80 – 120 employees",
    companyWebsite: "https://buffer.com",
    applicants: 44,
    responsibilities: [
      "Write SEO-optimised blog posts and long-form guides on social media topics.",
      "Manage and grow Buffer's newsletter (80k+ subscribers).",
      "Repurpose content across social media channels.",
      "Track and report on content performance metrics.",
      "Collaborate with the design team on visual content assets.",
    ],
    requirements: [
      "2+ years of content marketing or editorial experience.",
      "Excellent writing skills with a clear, engaging voice.",
      "Understanding of SEO fundamentals and on-page optimisation.",
      "Experience with CMS platforms (WordPress, Webflow).",
      "Data-driven mindset — comfortable interpreting analytics.",
    ],
    niceToHave: [
      "Experience growing an email newsletter.",
      "Video scripting or podcast coordination experience.",
      "Knowledge of Buffer's product.",
    ],
    benefits: [
      "100% remote — async-first team.",
      "Transparent salary formula.",
      "4 weeks PTO plus paid holidays.",
      "Annual team retreat.",
      "$500 remote work allowance.",
      "Book budget for professional development.",
    ],
  },
  12: {
    aboutCompany:
      "Duolingo is the world's most popular language learning platform, with over 500 million learners. Our app makes language learning fun, free, and effective through gamification, bite-sized lessons, and AI-powered personalisation.",
    experience: "3+ years",
    companySize: "700 – 1,000 employees",
    companyWebsite: "https://duolingo.com",
    applicants: 136,
    responsibilities: [
      "Build and maintain high-quality iOS application features in Swift.",
      "Optimise app performance, memory, and battery usage.",
      "Collaborate with product, design, and backend teams on new features.",
      "Write unit and UI tests to ensure code quality.",
      "Participate in code reviews and contribute to team engineering standards.",
    ],
    requirements: [
      "3+ years of iOS development experience.",
      "Proficiency in Swift and UIKit or SwiftUI.",
      "Strong understanding of iOS SDK, HIG, and app architecture patterns.",
      "Experience with CI/CD pipelines for mobile apps.",
      "Published apps in the App Store.",
    ],
    niceToHave: [
      "Experience with gamification or animation-heavy apps.",
      "Cross-platform mobile experience (React Native, Flutter).",
      "Knowledge of accessibility guidelines (WCAG for mobile).",
    ],
    benefits: [
      "Competitive salary + stock options.",
      "Premium health, dental, and vision benefits.",
      "Generous parental leave (18 weeks).",
      "Annual learning budget.",
      "Flexible hybrid schedule.",
      "Daily catered lunches in-office.",
    ],
  },
  13: {
    aboutCompany:
      "Atlassian makes tools like Jira, Confluence, and Trello that help 300,000+ customers worldwide collaborate better. We champion remote-first work and are known for our open, innovative culture and 'ShipIt' hack days.",
    experience: "5+ years",
    companySize: "10,000+ employees",
    companyWebsite: "https://atlassian.com",
    applicants: 59,
    responsibilities: [
      "Partner with engineering leaders on org design, performance, and succession.",
      "Drive end-to-end performance review cycles and feedback culture.",
      "Mediate employee relations issues with empathy and sound judgement.",
      "Analyse people metrics to identify trends and proactively address risks.",
      "Champion Atlassian's culture and values across the org.",
    ],
    requirements: [
      "5+ years of HRBP or people partner experience.",
      "Experience supporting large engineering organisations.",
      "Strong stakeholder management and influencing skills.",
      "Knowledge of Australian employment law.",
      "Data-driven — comfortable with Workday and Excel.",
    ],
    niceToHave: [
      "Experience in high-growth tech companies.",
      "Coaching qualification (ICF or similar).",
      "Background in organisational psychology.",
    ],
    benefits: [
      "Distributed-first, flexible work model.",
      "REMOTE allowance programme.",
      "Paid volunteer days (5 per year).",
      "Comprehensive health and wellbeing benefits.",
      "Generous equity + annual bonus.",
      "Access to Atlassian's full product suite.",
    ],
  },
  14: {
    aboutCompany:
      "Stripe is a financial infrastructure platform for businesses. Millions of companies use Stripe to accept payments, grow their revenue, and accelerate new business opportunities across Southeast Asia and globally.",
    experience: "4+ years",
    companySize: "4,000 – 6,000 employees",
    companyWebsite: "https://stripe.com",
    applicants: 72,
    responsibilities: [
      "Identify and evaluate strategic partnership opportunities across SEA.",
      "Negotiate and close partnership agreements with platform and ISV partners.",
      "Develop and execute the regional BD pipeline and go-to-market strategy.",
      "Collaborate with sales, product, and legal to structure partner deals.",
      "Represent Stripe at industry events and build executive-level relationships.",
    ],
    requirements: [
      "4+ years in business development, partnerships, or strategic sales.",
      "Strong network in the Southeast Asia tech ecosystem.",
      "Exceptional negotiation and deal structuring skills.",
      "Experience working cross-functionally in a fast-paced environment.",
      "Fluency in English; additional SEA language is a plus.",
    ],
    niceToHave: [
      "Background in payments, fintech, or marketplace businesses.",
      "Experience with API-first products.",
      "MBA or relevant postgraduate qualification.",
    ],
    benefits: [
      "Competitive package with equity.",
      "Comprehensive insurance for you and dependents.",
      "Annual learning stipend.",
      "Hybrid work model.",
      "Relocation support available.",
      "Company retreats across the Asia Pacific region.",
    ],
  },
  15: {
    aboutCompany:
      "Linear builds software for high-performance teams. Our issue tracker, project management, and roadmapping tools are used by the best engineering teams at companies like Vercel, Loom, and Retool. We care deeply about design and developer experience.",
    experience: "4+ years",
    companySize: "40 – 80 employees",
    companyWebsite: "https://linear.app",
    applicants: 175,
    responsibilities: [
      "Build product features across the React frontend and Node.js backend.",
      "Design and maintain GraphQL APIs for internal and external consumers.",
      "Optimise database queries and data models in PostgreSQL.",
      "Contribute to Linear's design system and component library.",
      "Participate in a lightweight on-call rotation.",
    ],
    requirements: [
      "4+ years of full-stack experience with TypeScript.",
      "Strong React skills and knowledge of modern state management.",
      "Experience with GraphQL APIs (Apollo or similar).",
      "Ability to work effectively in a small, autonomous team.",
      "High attention to product quality and performance.",
    ],
    niceToHave: [
      "Experience with real-time collaboration features.",
      "Design sensibility and Figma skills.",
      "Prior experience at a small startup.",
    ],
    benefits: [
      "Fully remote team across time zones.",
      "Equity with meaningful upside.",
      "Great health insurance.",
      "$1,500 annual equipment budget.",
      "Linear subscription (of course).",
      "Occasional team meetups in interesting cities.",
    ],
  },
  16: {
    aboutCompany:
      "Salesforce is the world's #1 CRM, bringing companies and customers together. With products for sales, service, marketing, commerce, and more — all built on a single trusted platform — we help businesses of every size grow and succeed.",
    experience: "3+ years",
    companySize: "70,000+ employees",
    companyWebsite: "https://salesforce.com",
    applicants: 203,
    responsibilities: [
      "Manage a portfolio of 20–30 enterprise accounts in the Northeast region.",
      "Drive new logo acquisition and expand existing accounts.",
      "Develop account strategies and multi-threaded stakeholder maps.",
      "Lead complex, consultant-led sales cycles from discovery to close.",
      "Forecast revenue accurately and maintain CRM hygiene.",
    ],
    requirements: [
      "3+ years of enterprise SaaS sales experience.",
      "Consistent track record of exceeding quota.",
      "Experience selling to VP and C-suite stakeholders.",
      "Strong command of consultative selling methodologies (MEDDIC, Challenger).",
      "Excellent written and verbal communication.",
    ],
    niceToHave: [
      "Experience selling Salesforce products.",
      "Knowledge of the financial services or healthcare verticals.",
      "Salesforce Certified Administrator or Sales Cloud Consultant.",
    ],
    benefits: [
      "Base + uncapped commission (OTE $180k–$220k).",
      "Equity awards (RSUs).",
      "Top-tier medical, dental, and vision.",
      "7 paid volunteer days per year.",
      "Generous parental leave.",
      "Top performer club trips (Presidents Club).",
    ],
  },
  17: {
    aboutCompany:
      "Canva is a global design platform on a mission to empower everyone to design anything. With 170+ million monthly active users across 190 countries, Canva is one of the world's fastest-growing SaaS companies.",
    experience: "3+ years",
    companySize: "3,000 – 4,000 employees",
    companyWebsite: "https://canva.com",
    applicants: 82,
    responsibilities: [
      "Create high-impact animations and motion graphics for product and marketing.",
      "Design video ads, social media animations, and launch videos.",
      "Collaborate with brand and product design teams to ensure motion consistency.",
      "Build reusable motion templates for internal and external use.",
      "Stay current with motion design trends and push creative boundaries.",
    ],
    requirements: [
      "3+ years of motion design experience.",
      "Advanced skills in After Effects, Premiere Pro, and Cinema 4D.",
      "Strong foundational design principles (typography, colour, composition).",
      "Experience creating animations for web and social platforms.",
      "A portfolio demonstrating a range of motion work.",
    ],
    niceToHave: [
      "Experience with Lottie/JSON animations for web.",
      "3D animation experience.",
      "Design skills in Figma or Canva.",
    ],
    benefits: [
      "Equity (Canva is pre-IPO!).",
      "Flexible hybrid work from Sydney HQ.",
      "Wellbeing allowance (AU$200/month).",
      "Parental leave (18 weeks full pay).",
      "Annual Vibe & Thrive allowance (AU$1,000).",
      "In-office chef and free lunches.",
    ],
  },
  18: {
    aboutCompany:
      "OpenAI is an AI safety company and the creator of ChatGPT, GPT-4, DALL-E, Sora, and Whisper. Our mission is to ensure that artificial general intelligence benefits all of humanity.",
    experience: "5+ years",
    companySize: "700 – 1,000 employees",
    companyWebsite: "https://openai.com",
    applicants: 519,
    responsibilities: [
      "Design and implement training pipelines for large language models.",
      "Run large-scale distributed training experiments on GPU clusters.",
      "Fine-tune and evaluate model performance across benchmarks.",
      "Collaborate with research scientists to translate ideas into production systems.",
      "Optimise inference efficiency and latency for deployed models.",
    ],
    requirements: [
      "5+ years of ML engineering or applied research experience.",
      "Deep expertise in PyTorch and large-scale distributed training.",
      "Strong Python programming skills.",
      "Understanding of transformer architectures and LLM training dynamics.",
      "Experience with large GPU cluster management (CUDA, NCCL).",
    ],
    niceToHave: [
      "Publications in NeurIPS, ICML, ICLR, or similar venues.",
      "Experience with RLHF and alignment techniques.",
      "Background in systems engineering for ML infrastructure.",
    ],
    benefits: [
      "Industry-leading compensation package.",
      "Significant equity stake.",
      "Top-tier health, dental, and vision benefits.",
      "Onsite meals and snacks.",
      "Generous parental leave (20 weeks).",
      "Annual research conference attendance budget.",
    ],
  },
  19: {
    aboutCompany:
      "Intercom is the complete AI-first customer service solution. We help businesses deliver exceptional support experiences at scale with our suite of AI features, live chat, tickets, and automation tools used by 25,000+ businesses.",
    experience: "4+ years",
    companySize: "900 – 1,200 employees",
    companyWebsite: "https://intercom.com",
    applicants: 98,
    responsibilities: [
      "Own the product roadmap for a key area of the Intercom platform.",
      "Define product strategy, prioritisation, and success metrics.",
      "Write detailed product requirements and user stories.",
      "Work closely with engineering and design in agile sprints.",
      "Gather and synthesise customer feedback to inform product decisions.",
    ],
    requirements: [
      "4+ years of product management experience in B2B SaaS.",
      "Strong analytical skills and data-driven decision making.",
      "Experience with agile development methodologies.",
      "Excellent stakeholder communication and prioritisation skills.",
      "Ability to think both strategically and tactically.",
    ],
    niceToHave: [
      "Experience with AI/ML product features.",
      "Background in customer support software.",
      "Technical degree or engineering background.",
    ],
    benefits: [
      "Competitive salary and equity.",
      "Premium health and dental insurance.",
      "Flexible hybrid work from London office.",
      "Annual learning budget (£1,500).",
      "Monthly social events.",
      "16 weeks paid parental leave.",
    ],
  },
  20: {
    aboutCompany:
      "CrowdStrike is a global cybersecurity leader protecting the world's critical enterprise infrastructure. Our AI-native Falcon platform stops breaches and delivers unparalleled protection against the most sophisticated adversaries.",
    experience: "2+ years",
    companySize: "8,000+ employees",
    companyWebsite: "https://crowdstrike.com",
    applicants: 67,
    responsibilities: [
      "Monitor security alerts and investigate potential incidents using Falcon.",
      "Perform threat hunting and anomaly detection across customer environments.",
      "Document and escalate security incidents following response procedures.",
      "Collaborate with client security teams during incident response engagements.",
      "Produce written threat intelligence reports for stakeholders.",
    ],
    requirements: [
      "2+ years in a SOC analyst or equivalent cybersecurity role.",
      "Hands-on experience with SIEM tools (Splunk, Elastic, or similar).",
      "Understanding of threat frameworks (MITRE ATT&CK).",
      "Strong English communication skills (written and verbal).",
      "CompTIA Security+, CEH, or equivalent certification preferred.",
    ],
    niceToHave: [
      "Experience with the CrowdStrike Falcon platform.",
      "GIAC certifications (GCIH, GCIA, or GCFE).",
      "Scripting skills (Python, PowerShell) for automation.",
    ],
    benefits: [
      "Competitive base salary.",
      "Performance-based bonus.",
      "Private health insurance.",
      "22 days annual leave.",
      "Remote work flexibility.",
      "CrowdStrike University training access.",
    ],
  },
  21: {
    aboutCompany:
      "Notion is on a mission to make it possible for every person and company to tailor their tools to their needs. We create a more connected and customisable workspace, used by teams at companies like Nike, Figma, and Pixar.",
    experience: "0–1 year",
    companySize: "500 – 800 employees",
    companyWebsite: "https://notion.so",
    applicants: 211,
    responsibilities: [
      "Support the marketing team in executing regional campaigns.",
      "Manage Notion's social media accounts for the DACH region.",
      "Help coordinate community events and ambassador activities.",
      "Create marketing content (copy, images, short-form video).",
      "Track campaign KPIs and produce weekly reports.",
    ],
    requirements: [
      "Currently enrolled in a bachelor's or master's programme (marketing, communications, or related).",
      "Strong written and verbal communication skills in English and German.",
      "Creative thinker with a passion for brand storytelling.",
      "Able to commit to a 5–6 month internship.",
      "Proficiency in Google Workspace and social media platforms.",
    ],
    niceToHave: [
      "Experience with Notion (personal or professional).",
      "Video editing skills (CapCut, Adobe Premiere).",
      "Previous internship in a tech company.",
    ],
    benefits: [
      "Competitive intern hourly rate (€18/hr).",
      "Real responsibility from day one.",
      "Access to Notion Team plan.",
      "Mentorship from senior marketing team members.",
      "Hybrid schedule (3 days in Berlin office, 2 remote).",
      "Intern socials and company events.",
    ],
  },
  22: {
    aboutCompany:
      "Shopify provides essential internet infrastructure for commerce, offering trusted tools to start, grow, market, and manage a retail business of any size. Shopify powers over 2 million businesses in 175+ countries.",
    experience: "2+ years",
    companySize: "10,000+ employees",
    companyWebsite: "https://shopify.com",
    applicants: 85,
    responsibilities: [
      "Own end-to-end recruiting for technical roles (engineering, data, product).",
      "Build and maintain talent pipelines through proactive sourcing.",
      "Screen candidates, coordinate interviews, and manage offers.",
      "Partner with hiring managers to understand role requirements and culture fit.",
      "Drive recruiting process improvements and candidate experience.",
    ],
    requirements: [
      "2+ years of technical recruiting experience.",
      "Familiarity with Boolean and LinkedIn Recruiter sourcing techniques.",
      "Experience using applicant tracking systems (Lever, Greenhouse).",
      "Strong interpersonal and negotiation skills.",
      "Ability to manage a high volume of requisitions simultaneously.",
    ],
    niceToHave: [
      "Experience recruiting globally across multiple time zones.",
      "Knowledge of Canadian employment regulations.",
      "Background in employer branding initiatives.",
    ],
    benefits: [
      "Competitive salary + bonus.",
      "Digital by default — fully remote.",
      "Equity (RSUs).",
      "Health, dental, vision, and life insurance.",
      "Parental leave (up to 26 weeks).",
      "$1,000 health and wellness stipend annually.",
    ],
  },
  23: {
    aboutCompany:
      "Amazon Web Services (AWS) is the world's most comprehensive and broadly adopted cloud platform, offering over 200 fully featured services. Millions of customers use AWS to lower costs, become more agile, and innovate faster.",
    experience: "8+ years",
    companySize: "100,000+ employees",
    companyWebsite: "https://aws.amazon.com",
    applicants: 41,
    responsibilities: [
      "Lead cloud migration assessments and architecture workshops for enterprise clients.",
      "Design multi-account AWS landing zones using best-practice security controls.",
      "Produce solution architecture documents and reference architectures.",
      "Advise clients on cost optimisation, resilience, and well-architected frameworks.",
      "Collaborate with AWS account teams on pre-sales and delivery engagements.",
    ],
    requirements: [
      "8+ years of cloud architecture or infrastructure experience.",
      "AWS Solutions Architect Professional certification required.",
      "Deep expertise in AWS services (EC2, EKS, RDS, S3, IAM, VPC, etc.).",
      "Experience delivering large-scale enterprise cloud migrations.",
      "Strong communication skills for executive-level presentations.",
    ],
    niceToHave: [
      "AWS Security or Database Specialty certifications.",
      "Experience with multi-cloud environments (Azure, GCP).",
      "Background in financial services or healthcare cloud compliance.",
    ],
    benefits: [
      "Premium contract rate ($150–$200/hr).",
      "Project length: 6–12 months with extension possibility.",
      "Remote with occasional on-site client visits.",
      "AWS employee discount on cloud services.",
      "Access to AWS internal training platform.",
      "Travel and expenses covered.",
    ],
  },
  24: {
    aboutCompany:
      "Revolut is a fintech super-app with 35+ million customers globally. We offer banking, trading, crypto, and payments services — and we're on a mission to build the world's first truly global financial super-app.",
    experience: "5+ years",
    companySize: "6,000+ employees",
    companyWebsite: "https://revolut.com",
    applicants: 57,
    responsibilities: [
      "Manage month-end, quarter-end, and year-end close processes.",
      "Produce consolidated financial statements across 20+ global entities.",
      "Own regulatory reporting submissions to the FCA and partner banks.",
      "Lead and develop a team of 4 management accountants.",
      "Implement process improvements and automation in finance workflows.",
    ],
    requirements: [
      "5+ years in a finance controller or senior accountant role.",
      "ACA, ACCA, or CIMA qualified.",
      "Strong technical accounting knowledge (IFRS/UK GAAP).",
      "Experience managing international regulatory reporting.",
      "Advanced Excel; experience with ERP systems (NetSuite preferred).",
    ],
    niceToHave: [
      "Experience in fintech, banking, or regulated financial services.",
      "Exposure to crypto or digital asset accounting.",
      "Knowledge of FCA regulatory reporting requirements.",
    ],
    benefits: [
      "Competitive salary and bonus.",
      "Revolut Premium account.",
      "Private health insurance.",
      "Hybrid work model (London HQ).",
      "Shareholding programme.",
      "Free daily team lunches at the office.",
    ],
  },
};

/** Fully merged Job objects (base + detail) */
export const enrichedJobs = dummyJobs.map((job) => ({
  ...job,
  ...(jobDetails[job.id] ?? {}),
})) as Job[];
